from pydantic import BaseModel, Field

class QueryRequest(BaseModel):
    query: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user query to be processed by an LLM."
    )

class QueryResponse(BaseModel):
    llm_used: str = Field(..., description="The name of the LLM that processed the query.")
    response: str = Field(..., description="The final response generated by the selected LLM.")